name: equatable_custom_lint
version: 1.0.1
description: This is a set of rules to make classes using Equatable more
  maintainable. We make sure here that every fields in an Equatable class is
  linked to the Equatable props getter.
homepage: https://github.com/thecodebrothers/equatable_lint
repository: https://github.com/thecodebrothers/equatable_lint

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: "^7.0.0"
  analyzer_plugin: ^0.13.0
  collection: ^1.18.0
  custom_lint_builder: "^0.7.5"
  equatable: ^2.0.7
